import type { Metadata } from "next";
import { Crimson_Text, DM_Sans, Roboto_Mono } from "next/font/google";
import "./globals.css";

const crimsonText = Crimson_Text({
  subsets: ["latin"],
  variable: "--ff-primary",
  weight: ["400", "600", "700"],
});
const dmSans = DM_Sans({ subsets: ["latin"], variable: "--ff-secondary" });
const robotoMono = Roboto_Mono({ subsets: ["latin"], variable: "--ff-accent" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${crimsonText.variable} ${dmSans.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
